name: airbnb
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  another_carousel_pro: ^1.0.2
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  custom_info_window: ^1.0.1
  google_maps_flutter: ^2.10.0
  chat_gpt_sdk: ^3.1.0
  dash_chat_2: ^0.0.21
  google_generative_ai: ^0.4.6
  geolocator: ^13.0.2
  shared_preferences: ^2.3.4
  flutter_paypal_payment: ^1.0.7
  flutter_dotenv: ^5.0.2 
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  fl_chart: ^0.70.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker.png
